### ISSUE TITLE
초기 클래스 셋팅

### ISSUE THREAD

**Issue by yjll1019** [711skhu/admin#2]
Controller, Service, ServiceImpl 생성하기

- Controller 목록
MemberController
CourseController
ProblemController
CommentController
SolutionController

- Service/ServiceImpl 목록
MemberService/MemberServiceImpl
CourseService/CourseServiceImpl
ProblemService/ProblemServiceImpl
CommentService/CommentServiceImpl
SolutionService/SolutionServiceImpl

**Comment by shouwn** [comment]
초키 클래스 셋팅을 적은 건 좋지만 코드를 보면 알 수 있는 것이라
이 내용은 이슈로 안 올려도 될 것 같네요.

기능들을 이슈로 올려서 상세 구현을 commit을 나타내 표현해주시면 좋을 것 같아요

추가로 Service 계층에 인터페이스를 두셨는데 두신 이유가 있나요?

**Comment by yjll1019** [comment]
네~
인터페이스를 사용한 이유는 현재는 인터페이스를 1개의 클래스만 implements를 하는 구조이지만,
혹시나 다른 클래스에서도 implements 를 해야하는 상황이 있을 수도있지 않을까 하는 생각에 두려고했습니다~~! 다른 분들의 의견따라서 수정하겠습니다~~! 
그리고 이 이슈는 인터페이스에 대한 답변을 받은 후에 클로즈하겠습니다!

**Comment by shouwn** [comment]
현재 개발 초기 단계이기 때문에 Service 인터페이스가 빈번히 수정될 것이라 생각하여
인터페이스가 필요한 경우에 생성하는 편이 좋다고 생각합니다.

**Comment by yjll1019** [comment]
네 그럼 인터페이스 없이 진행하도록 하겠습니다~
